### ISSUE TITLE
Problems with symlinked dependencies in monorepos and phantom dependencies

### ISSUE THREAD

**Issue by javier-garcia-meteologica** [modernweb-dev/web#1039]
Since @open-wc/testing-karma is deprecated I'm migrating to @web/test-runner.

There are 2 big incompatibilities with monorepos.

### esbuild duplicates symlinked lit-html instances

This problem is related to https://github.com/Polymer/lit-element/issues/390. Lit-html module should only be imported once, otherwise it will render `[object Object]`. The module loader should cache the first 'lit-html' call and server always the same module.

Note that `preserveSymlinks: true` is necessary. Without it web-test-runner will complain that @open-wc/testing is outside of the project directory.

### web-test-runner referencees phantom dependencies

web-test-runner assumes that `node_modules` contains all explicit and implicit dependencies of the project. But this is incompatible with `pnpm`.

### Reproduction

The problems can be reproduced in this repo:

https://github.com/javier-garcia-meteologica/test-runner-lit-hml-monopero-symlink-issue

```
$ git clone https://github.com/javier-garcia-meteologica/test-runner-lit-hml-monopero-symlink-issue
$ cd test-runner-lit-hml-monopero-symlink-issue
$ rush install
$ rush build
$ cd lit-element-ts-esbuild
$ yarn run test
```

I modified the code to log `this.shadowRoot.innerHTML` to the console. The tests will fail because lit-html is imported more than once and it's rendering those pesky `[object Object]`.

```
 🚧 Browser logs:
      <!---->[object Object]<!---->
      <!---->[object Object]<!---->
      <!---->[object Object]<!---->
      <!---->[object Object]<!---->

 ❌ MyElement > increases the counter on button click
      at: test/my-element.test.ts:16:44
      TypeError: Cannot read property 'click' of null
        at n.<anonymous> (test/my-element.test.ts:16:44)
```

`rush` uses `pnpm` as a package manager by default, but this repository had to switch to `yarn` so that `web-test-runner` finds phantom dependencies.

To replicate the problem of phantom dependencies, edit the file `<monorepo_root>/rush.json`, uncomment `"pnpmVersion"` and comment out `"yarnVersion"`.

```
"pnpmVersion":"4.14.4",
//"npmVersion":"4.5.0",
//"yarnVersion":"1.9.4",
```

Now purge the monorepo and rebuild

```
$ rm <monorepo_root>/common/config/rush/yarn.lock
$ rush update --full --purge
$ rush build
```

Running tests will fail and the errors will look like these:

```
TypeError: Failed to resolve module specifier "@open-wc/testing-helpers". Relative references must start with either "/", "./", or "../".
TypeError: Failed to resolve module specifier "chai/chai.js". Relative references must start with either "/", "./", or "../".
```

**Comment by LarsDenBakker** [comment]
**esbuild duplicates symlinked lit-html instances:** I don't quite follow what you mean here. Are you using the esbuild plugin? How is it duplicating exactly?

The thing with symlinks is that you preserve them, then you will load two instances if they have different urls. The browser deduplicates based on module URL only.

**web-test-runner referencees phantom dependencies** to be exact, WTR doesn't expect anything. it just serves your code to the browser as is. The browser needs to be able to access the URLs since it will request those from your file system directly.

The node resolve flag will resolve your bare imports, and try to find them on the file system. You can extend the root directory to allow serving from other directories as well.

PNPM creates a unique challenge for developing with es modules in the browser. It's based on symlinks, so we should be respecting those. But that will create multiple instances of a module.. I'm not sure how we could tackle this right now.

**Comment by javier-garcia-meteologica** [comment]
Regarding **duplicated symlinked lit-html** instances

Yes, I'm using the esbuildPlugin. The monorepo needs `preserveSymlinks: true`, otherwise it would try to serve the modules from outside of the project folder and throw an error. The project and all of the dependencies import `lit-element` or `lit-html` which all should resolve to the same module. The problem is that identical import tokens ('lit-html`) are resolved by esbuildPlugin to different modules depending on whether the import statement is located: in the main project or in a dependency.

I agree with you. The most likely explanation is that `preserveSymlinks: true` causes them to be "in two separate directories" and therefore they are assigned different urls.

I've tried other solutions. For instance I tried to use `rootDir: '../common/temp'` which points to the directory containing `node_modules`. But this creates another problem because now web-test-runner cannot find the test file.

```
test/my-element.test.ts:

 🚧 Browser logs:
      TypeError: Failed to fetch dynamically imported module: http://localhost:9407/lit-element-ts-esbuild/test/my-element.test.ts?wtr-session-id=feac751a-568b-45ae-ba6c-4503072ef8a5

 🚧 404 network requests:
    - lit-element-ts-esbuild/test/my-element.test.ts?wtr-session-id=feac751a-568b-45ae-ba6c-4503072ef8a5

 ❌ Could not import your test module. Check the browser logs or open the browser in debug mode for more information.
```

**Comment by LarsDenBakker** [comment]
Esbuild doesn't resolve the imports, that's what the node-resolve plugin does. When you use `--node-resolve`, we add  `@rollup/plugin-node-resolve`. What you're describing is how the node resolution works, imports are resolved relative to the importer.

You can try using the dedupe option, that will always resolve lit-html from the root:

```js
export default {
  nodeResolve: {
    dedupe: ['lit-html']
  }
}
```

or 

```js
export default {
  nodeResolve: {
    dedupe: true
  }
}
```

That's not quite the right solution I want for this in the long term, since we need to be able to support multiple versions of a single package.

**Comment by javier-garcia-meteologica** [comment]
I tried to use `nodeResolve: { dedupe: ['lit-html'] }`. If `preserveSymlinks: true` is kept there is no deduplication, and if it's dropped then the initial problem with symlinked dependencies appears .

```
Error while transforming test/my-element.test.ts:                                                                                                                                                                   
                                                                                                                                                                                                                    
Resolved @open-wc/testing to <path>/test-runner-lit-hml-monopero-symlink-issue/common/temp/node_modules/@open-wc/testing/index.js.                                                                  
                                                                                                                                                                                                                    
This path is not reachable from the browser because it is outside root directory <path>/test-runner-lit-hml-monopero-symlink-issue/lit-element-ts-esbuild
```

**Comment by LarsDenBakker** [comment]
Yeah, I meant to use both of those options.

**Comment by javier-garcia-meteologica** [comment]
Theoretically bundling could solve all these problems. I found out `rollupBundlePlugin` and decided to give it a try.

```
import { rollupBundlePlugin } from '@web/dev-server-rollup';
import nodeResolve from '@rollup/plugin-node-resolve';
import typescript from 'rollup-plugin-typescript2';

export default {
  plugins: [
    rollupBundlePlugin({
      rollupConfig: {
        input: ['./test/my-element.test.ts'],
        plugins: [
          nodeResolve(),
          typescript()
        ]
      }
    })
  ],
};
```

Unfortunately it didn't work. The documentation mentions that `@rollup/plugin-typescript` doesn't work at the moment and perhaps there is a similar problem with `rollup-plugin-typescript2`.

```
$ yarn run web-test-runner
yarn run v1.21.1
$ <path>/test-runner-lit-hml-monopero-symlink-issue/lit-element-ts-esbuild/node_modules/.bin/web-test-runner
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten

(node:1618555) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Object.getTestProgressReport (<path>/test-runner-lit-hml-monopero-symlink-issue/common/temp/node_modules/@web/test-runner-cli/dist/reporter/getTestProgress.js:26:78)
    at Object.getTestProgress (<path>/test-runner-lit-hml-monopero-symlink-issue/common/temp/node_modules/@web/test-runner-cli/dist/reporter/defaultReporter.js:47:38)
    at TestRunnerCli.reportTestProgress (<path>/test-runner-lit-hml-monopero-symlink-issue/common/temp/node_modules/@web/test-runner-cli/dist/cli/TestRunnerCli.js:273:100)
    at TestRunnerCli.switchMenu (<path>/test-runner-lit-hml-monopero-symlink-issue/common/temp/node_modules/@web/test-runner-cli/dist/cli/TestRunnerCli.js:330:22)
    at TestRunnerCli.start (<path>/test-runner-lit-hml-monopero-symlink-issue/common/temp/node_modules/@web/test-runner-cli/dist/cli/TestRunnerCli.js:64:14)
    at Object.startTestRunner (<path>/test-runner-lit-hml-monopero-symlink-issue/common/temp/node_modules/@web/test-runner-cli/dist/startTestRunner.js:32:9)
(node:1618555) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejectionid: 1)
(node:1618555) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by LarsDenBakker** [comment]
Can you try with the latest test-runner/dev-server? I've made it possible to resolve modules to any location.

**Comment by javier-garcia-meteologica** [comment]
Thank you for your dedication. Unfortunately the issue is still present on the latest release.

 ```
"@web/dev-server": "0.1.0",
"@web/dev-server-esbuild": "0.2.9",
"@web/test-runner": "0.11.0",
```

dev-server on http://localhost:8000/demo/ serves this:

```
 [object Object]
```
 
 And tests have the same problem
 
 ```
> web-test-runner test/**/*.test.ts --node-resolve


test/my-element.test.ts:

 🚧 Browser logs:
      [object Object]
      [object Object]
      [object Object]
      [object Object]

 ❌ MyElement > increases the counter on button click
      at: test/my-element.test.ts:16:44
      TypeError: Cannot read property 'click' of null
        at o.<anonymous> (test/my-element.test.ts:16:44)

Chrome: |██████████████████████████████| 1/1 test files | 3 passed, 1 failed

Finished running tests in 0.6s with 1 failed tests.

 ERROR  Test failed. See above for more details.
 ```
 
Using pnpm instead of yarn makes module resolution of sub dependencies fail
 
 ```
 Error while transforming node_modules/.pnpm/@open-wc/testing@2.5.32/node_modules/@open-wc/testing/index.js: Could not resolve import "@open-wc/testing-helpers"
 ```

**Comment by javier-garcia-meteologica** [comment]
Finally I found out which were the remaining problems and how to solve them. First, `preserveSymlinks: true` should NOT be used because the only way to solve non-hoisted pnpm dependencies is to resolve the symlinks and, from the resolved directory, traverse parent directories looking up for node_modules with those dependencies. Thanks to @LarsDenBakker package resolution in pnpm works fine without `preserveSymlinks`.

Therefore, the configuration should be:

```js
export default {
  nodeResolve: { dedupe: ['lit-html'] },
  plugins: [esbuildPlugin({ ts: true })]
}
```

This will almost work, expect it won't resolve `lit-html`.

```
Error while transforming ../common/temp/node_modules/.pnpm/registry.npmjs.org/lit-element/2.4.0/node_modules/lit-element/lit-element.js: Could not resolve import "lit-html/lib/shady-render.js".
  54 |  * @packageDocumentation
  55 |  */
> 56 | import { render } from 'lit-html/lib/shady-render.js';
     |                        ^
  57 | import { UpdatingElement } from './lib/updating-element.js';
  58 | export * from './lib/updating-element.js';
  59 | export * from './lib/decorators.js';
```

That's because @rollup/node-resolve assumes that deduplicated dependencies are placed in the main `node_modules` directory of our project.

https://github.com/rollup/plugins/blob/0e4f0142a9c44074ae8a5df86f9442b119a9978c/packages/node-resolve/src/index.js#L109

```js
      const baseDir = !importer || dedupe(importee) ? rootDir : dirname(importer);
```

Perhaps lit-html@2 won't need to be deduped, but so far we have to deal with it. So if we have deduplicated dependencies we need to add them as dependencies or devDependencies of our main project, even if they are not used directly.

```sh
# If you use rush
rush add --dev lit-html
# If you use pnpm directly to manage your monorepo
pnpm add -D lit-html
```

And that's all, now everything should work!

**Comment by LarsDenBakker** [comment]
If both projects use a compatible semver range, it should solve to only one version of lit-html/lit-element. Doesn't that work with PNPM?

**Comment by javier-garcia-meteologica** [comment]
Yes, it resolves to only one version of lit-html. The question is how that unique location is determined.

The [structure](https://pnpm.js.org/en/symlinked-node-modules-structure) of `node_modules` in pnpm is quite complex. Resolution works like this:

1. Go to `node_modules` and find dependency
2. Resolve dependency symlink (now is in another route)
3. From this new route, traverse the directory tree upwards looking for `node_modules`
4. Repeat step 1

Here is an example for our project which is in directory `<monorepo_path>/lit-element-ts-esbuild`

- Find dependency in `<monorepo_path>/lit-element-ts-esbuild/node_modules/@open-wc/testing`
- It's a symlink, resolve it. Now we are in `<monorepo_path>/common/temp/node_modules/.pnpm/@open-wc/testing@2.5.32/node_modules/@open-wc/testing`
- While processing `@open-wc/testing`, `@open-wc/testing-helpers` needs to be imported
- Nothing is found in `<monorepo_path>/common/temp/node_modules/.pnpm/@open-wc/testing@2.5.32/node_modules/@open-wc/testing/node_modules/@open-wc/testing-helpers`, so traverse direcotry tree upwards.
- `@open-wc/testing-helpers` is found in  `<monorepo_path>/common/temp/node_modules/.pnpm/@open-wc/testing@2.5.32/node_modules/@open-wc/testing-helpers`
- This this new location is a symlink, resolve it. Now we are in `<monorepo_path>/common/temp/node_modules/.pnpm/@open-wc/testing-helpers@1.8.12/node_modules/@open-wc/testing-helpers/`
- While processing `<monorepo_path>/common/temp/node_modules/.pnpm/@open-wc/testing-helpers@1.8.12/node_modules/@open-wc/testing-helpers/src/lit-html.js`, `lit-html` needs to be imported

## Without deduplication

At this point and without deduplication, @rollup/node-resolve evaluates

```js
      const baseDir = dirname(importer);
```

Which uses `<monorepo_path>/common/temp/node_modules/.pnpm/@open-wc/testing-helpers@1.8.12/node_modules/@open-wc/testing-helpers/src/` as `baseDir`. From this location it traverses upwards and finds `lit-html` in `<monorepo_path>/common/temp/node_modules/.pnpm/@open-wc/testing-helpers@1.8.12/node_modules/lit-html`.

In this scenario everything works fine except lit-html, which has duplicated imports.

## With deduplication

With deduplication, @rollup/node-resolve expression evaluates to:

```js
      const baseDir = rootDir;
```

Which uses `<monorepo_path>/lit-element-ts-esbuild` as `baseDir`. Pnpm only exposes direct dependencies in the `node_modules` of the project.

```bash
$ ls <monorepo_path>/lit-element-ts-esbuild/node_modules
lit-element  @open-wc  tslib  @types  typescript  @web
```

Since `lit-html` is not a direct dependency, nothing is found and it throws an error. Fortunately it's easy to work around this, just add `lit-html` as a direct (dev)dependency and it will work.

**Comment by LarsDenBakker** [comment]
So PNPM duplicates dependencies for each package? That seems like it will be quite problematic, not only for lit-html but for other packages as well. You're sending a lot of duplicate code to the end user.

**Comment by javier-garcia-meteologica** [comment]
Generally it doesn't duplicate dependencies, they are just symlinks. However it can duplicate dependencies if dependency versions are incompatible between two packages.

**Comment by LarsDenBakker** [comment]
Ah right, but then by following the symlinks only one version of lit-html will be loaded in the end if the versions are compatible.

**Comment by javier-garcia-meteologica** [comment]
Oh you are right :0

Cleaned the config and just this is enough, everything was working

```js
export default {
  plugins: [esbuildPlugin({ ts: true })]
}
```

```bash
web-test-runner --node-resolve \"test/**/*.spec.ts\""
```
