### ISSUE TITLE
`@web/storybook-builder`: issue with `build` of the `docs` addon

### ISSUE THREAD

**Issue by florian-sanders-cc** [modernweb-dev/web#2505]
## Context

I work for [Clever Cloud] and we use many packages from modern-web.

We saw you had published a `storybook-builder` package and decided to give it a try because we'd like to upgrade our storybook but we want to keep using mostly the Modern Web stack (dev server, test runner, etc., :heart: ).

## Issue

In our project, we rely on the docs addon / [autodocs](https://storybook.js.org/docs/web-components/writing-docs/autodocs).

We have faced two issues with `autodocs` and `@web/storybook-builder`:

- the `autodocs` feature relies on `tocbot` and it uses `commonjs` imports. We solved this by using the `commonjs` rollup plugin in `wdsFinal`. It worked for our `dev` setup but not for the `build`.
- the build itself goes fine but when serving the build result, the docs pages (auto generated) fail to load in the browser. We end up with a blank story iframe and the following error in the browser console:
```js
Uncaught (in promise) TypeError: __export9$1 is not a function 
<anonymous> http://localhost:6006/DocsRenderer-NNNQARDV-b4b5d8e8.js:9068
DocsRenderer-NNNQARDV-b4b5d8e8.js:9068:2631
```

## Reproduction

To make sure this was not related to our code, I've create a repo with minimal dependencies and code.

 There is `readme` to explain how to reproduce but it's fairly straightforward:
https://github.com/florian-sanders-cc/storybook-builder-test

Feel free to tell me if I can help with more details.
Thanks a lot for your time and your work :clap:

**Comment by bashmish** [comment]
Did you check "rollupFinal" API?  You might need to set it up too for CommonJS.

**Comment by florian-sanders-cc** [comment]
I've tested again and I got the same result.

I've updated the reproduction repository with this change as well so you can check (if you want and if/when you have time :wink:)

**Comment by bashmish** [comment]
I see you are also using "autodocs" and I must say that I didn't invest a lot of time in testing that.

Some of the Storybook dependencies are not just CommonJS, but also use Node specific APIs in the sources, so you might run into also kinds of compatibility issues. We decided to only support the core Storybook functionality, essential plugins and such which are expected to work out of the box. From your example I see that it should be working out-of-the-box, it's pretty straighforward, so I'd say we should make it work and shouldn't even require a custom CommonJS plugin setup.

Do you feel like contributing a fix for this? I think the solution is to find out which exact dependency (tocbot itself or some of it's dependencies) is not browser-cpmpatible and update this internal plugin to prebundle it for the browser https://github.com/modernweb-dev/web/blob/master/packages/storybook-builder/src/rollup-plugin-prebundle-modules.ts You might need a bit more that just adding a candidate in the array as there might always be some new Node or non-standard stuff you find on NPM that the plugin doesn't transform yet.

**Comment by florian-sanders-cc** [comment]
> Do you feel like contributing a fix for this? 
Gladly, I'm not very experienced when it comes to tooling and bundling but I'll give it a try. Thanks for your explanations :wink:.

I've added `tocbot` and `@storybook/blocks` to the array and it did solve two issues:
- I don't have to use the `commonjs` rollup plugin with the WDS anymore,
- With the built storybook, the `TypeError: __export9$1 is not a function` error is gone but now I have a `TypeError: __export9$2 is not a function` error.

I've tried adding all `tocbot` dependencies (but it only has `dev` dependencies) and all `@storybook/addon-docs` dependencies but it did not solve the issue.

Some of the `@storybook/addon-docs` dependencies relied on Node as you said so I couldn't add them to the list without making the prebundle fail (`fs-extra`, etc.).

I'll continue tonight but I'm not sure where to go next at the moment :eyes:

**Comment by florian-sanders-cc** [comment]
Actually, I'm not sure it changed much for the build.
If I look at the `DocsRenderer...` file which generates the error, `__export9$1` was related to the `createContext` react hook:
```js
createContext: () => __export9$1,
```
and after adding `tocbot` + `@storybook/blocks` to the prebundle candidates:
```js
createContext: () => __export9$2,
```

So I'm guessing the issue is still the same.

I see `react` & `react-dom` are among the candidates so I'm not sure what to do. 

Do you think it could be related to the fact that `@storybook/addon-docs` uses `react 16` while `storybook` uses `react 18`?

**Comment by florian-sanders-cc** [comment]
Thanks again for your answer and sorry that I haven't been able to help more.

Your explanation is very clear so I'll try to dig a bit further when I have time but I doubt I'll solve the issue (if I do I'll keep you posted of course).

**Comment by bashmish** [comment]
@florian-sanders-cc I updated the list of packages to only bundle what's really necessary in #2508

can you please have a look and give it another try? it doesn't necessarily fix your issue, but you might see from my PR what kind of dependencies and why you need to target

**Comment by florian-sanders-cc** [comment]
Unfortunately the build doesn't work anymore with `@web/storybook-builder v0.1.3`.

I wonder why it would not work on my side but it worked fine on yours? (I tried disabling `autodocs` but it did not change anything)

Anyway, I looked at your comments and tried to follow the same logic to fix my build (thanks for the comments :+1:).
I've added the following to make it work but in the end I'm back to square one with the `__export9$1 is not function` error in my browser:
```js
   /**
     * dependency of '@storybook/react-dom-shim' (https://cdn.jsdelivr.net/npm/@storybook/react-dom-shim@7.5.1/dist/react-16.mjs)
     * exports rely on commonjs: https://cdn.jsdelivr.net/npm/react-dom@18.2.0/index.js
     */ 
    'react-dom',
    /**
     * dependency of '@storybook/theming' (https://cdn.jsdelivr.net/npm/@storybook/theming@7.5.1/dist/index.mjs) 
     * `import * as React from 'react';
     * import { forwardRef, useContext } from 'react';`
     * exports rely on commonjs: https://cdn.jsdelivr.net/npm/react@18.2.0/index.js
     */
    'react',
    /**
     * dependency of '@storybook/theming' (https://cdn.jsdelivr.net/npm/@storybook/theming@7.5.1/dist/index.mjs)
     * `import memoize2 from 'memoizerific';`
     * exports rely on commonjs: https://cdn.jsdelivr.net/npm/memoizerific@1.11.3/src/memoizerific.js
     */
    'memoizerific',
    /**
     * dependencies of '@storybook/blocks' (https://cdn.jsdelivr.net/npm/@storybook/blocks@7.5.1/dist/index.mjs)
     * they all rely on commonjs (https://cdn.jsdelivr.net/npm/lodash@4.17.21/uniq.js for instance)
     */
    'lodash/uniq.js',
    'lodash/pickBy.js',
    'lodash/cloneDeep.js',
    'lodash/throttle.js',
    /**
     * dependency of '@storybook/dist/Color-[hash].msj' (https://cdn.jsdelivr.net/npm/@storybook/blocks@7.5.1/dist/Color-6VNJS4EI.mjs)
     * exports rely on commonjs: https://cdn.jsdelivr.net/npm/color-convert@2.0.1/index.js 
     */
    'color-convert',
```

I know you have a lot on your plate so don't feel pressure to answer right away, I'll try my best in the meantime and if I can't find the solution then you will when you have time :wink:

I'll give it another try tomorrow!

**Comment by florian-sanders-cc** [comment]
I managed to find a workaround but I'm pretty sure the solution is not good because I use `rollupCommonjs` without `include` for the build :see_no_evil:.

Although it not a good solution, this does solve both the `dev` and `build` issues I had with the `autodocs` feature.

In case it helps, I created a fake pull request on my fork to highlight the changes : https://github.com/florian-sanders-cc/web/pull/1/files
